#!/bin/bash


# debian 基础环境
sudo apt update && sudo apt -y upgrade && sudo apt install -y docker docker.io docker-compose &&  sudo systemctl enable docker && sudo systemctl start docker 

# 配置文件
sudo cp -rf conf/config.simple.ini conf/config.ini